Bostads-AB-Mimer/onecore-core

src/adapters/leasing-adapter.ts, src/services/lease-service/index.ts
Endpoint currently broken because it returns axios response as responsedata, rather than the body.
=> fix: return response data when fetching listing by id

package.json, src/processes/parkingspaces/internal/index.ts, src/processes/parkingspaces/internal/tests/index.test.ts
Fixes a couple of broken tests in core/parkingspaces/internal
=> 1426: fix broken tests for parkingspaces

src/services/ticketing-service/index.ts, src/services/ticketing-service/tests/index.test.ts, src/services/ticketing-service/tests/mockData.ts
update test to fit changes in endpoint
=> 1432-fix-create-ticket-test

src/processes/parkingspaces/internal/tests/index.test.ts
* Fix for failing tests
* two additional tests for credit check
=> Fix: Failing tests for createNoteOfInterest

.eslintrc, .github/workflows/ci.yml, .github/workflows/lint-and-test.yml, package-lock.json, package.json, src/processes/parkingspaces/internal/tests/create-note-of-interest.mocks.ts
Adds workflow to test, lint and check ts on PR:s against main. Also depend on the job in the "ci" job.
Fixes https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1525
=> chore: 1525 - Lint, test and check TS on CI

src/adapters/leasing-adapter.ts, src/adapters/types.ts, src/app.ts, src/processes/parkingspaces/internal/create-offer.ts, src/services/lease-service/index.ts, src/services/lease-service/tests/index.test.ts, src/services/property-management-service/index.ts, test/factories/contact.ts
- Get contact by search query
- Get contact by contact code
=> feat: 1387 - Create note of interest

src/adapters/tests/leasing-adapter.mocks.ts, src/adapters/tests/leasing-adapter.test.ts, src/processes/parkingspaces/internal/tests/create-note-of-interest.test.ts, src/services/lease-service/tests/index.test.ts, test/factories/contact.ts, test/factories/index.ts, test/factories/offer.ts
https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Dev/Issues/?workitem=1538
some refactors to use factories instead of hardcoded mocks. There are more possible refactors for the future but these are the obvious and not so intrusive ones.
=> feat: 1538 refactor test to use factories

package-lock.json, package.json, src/adapters/leasing-adapter.ts, src/services/lease-service/index.ts, src/services/lease-service/tests/index.test.ts, test/factories/index.ts, test/factories/offer.ts
https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1574
=> feat: 1574 offer details endpoint 

package-lock.json, package.json, src/adapters/communication-adapter.ts, src/processes/parkingspaces/internal/create-offer.ts
* Throw error if we're trying to send email to contacts without email address
=> Feat: 1550 Handle null email from DB

src/adapters/leasing-adapter.ts, src/services/lease-service/index.ts
Adds route roundtrip to leasing for deleting a listing
=> MIM-87: Delete listing

src/adapters/leasing-adapter.ts, src/processes/parkingspaces/internal/create-note-of-interest.ts, src/processes/parkingspaces/internal/tests/create-note-of-interest.test.ts
https://linear.app/mimer-onecore/issue/MIM-90/det-nya-svarsformatet-gor-att-create-note-of-interest-inte-skapar-upp
=> MIM-90: Fix create-note-of-interest with new adapter result format

src/adapters/leasing-adapter.ts, src/adapters/tests/leasing-adapter.test.ts, src/processes/parkingspaces/internal/DOCS_Accept_Offer.md, src/processes/parkingspaces/internal/reply-to-offer.ts, src/processes/parkingspaces/internal/tests/reply-to-offer.test.ts, src/services/lease-service/index.ts, src/services/lease-service/tests/index.test.ts
* Accept offer gets applicant and offer
=> Feat:mim-27 Accept Offer, get Applicant and offer

src/adapters/leasing-adapter.ts, src/processes/parkingspaces/internal/reply-to-offer.ts, src/processes/parkingspaces/internal/tests/reply-to-offer.test.ts
- Adds a route to listing to close offer on accepting offer
- Call route from accept-offer process
- Fixes some tests
=> MIM-49 - Close offer round on accept offer

src/processes/parkingspaces/internal/reply-to-offer.ts
* Fixed bug where listing date was interpreted wrong
=> Feat: Mim-32 Answer Offer Confirmation

src/processes/parkingspaces/internal/create-offer.ts
https://linear.app/mimer-onecore/issue/MIM-142/berakna-housingleasestatus-i-create-offer
=> MIM-142: Determine housing lease status for offer applicant when creating offer

package-lock.json, package.json, src/adapters/leasing-adapter.ts, src/adapters/tests/leasing-adapter.mocks.ts, src/adapters/types.ts, src/services/lease-service/index.ts, src/services/lease-service/tests/index.test.ts
https://linear.app/mimer-onecore/issue/MIM-171/fixa-till-befintliga-listings-flikar
=> MIM-171: get active offer

package-lock.json, package.json, src/adapters/leasing-adapter.ts, src/adapters/tests/leasing-adapter.test.ts, src/processes/parkingspaces/internal/create-offer.ts, src/processes/parkingspaces/internal/tests/create-offer.test.ts, src/services/lease-service/index.ts, src/services/lease-service/tests/index.test.ts
https://linear.app/mimer-onecore/issue/MIM-169/lagg-till-listing-status-noapplicants-samt-closed
=> MIM-169: Create offer - Update listing status when no applicants

src/adapters/leasing-adapter/index.ts, src/adapters/leasing-adapter/offers.ts, src/adapters/tests/leasing-adapter/offers.test.ts, src/processes/parkingspaces/internal/create-offer.ts, src/processes/parkingspaces/internal/tests/create-offer.test.ts
Update offer sentAt
- after email has been successfully sent to applicant.
- dont fail if it fails, just notify dev (?)
=> UTH-1: Update offer sent at

src/processes/parkingspaces/internal/reply-to-offer.ts, src/processes/parkingspaces/internal/tests/reply-to-offer.test.ts
Fixes https://linear.app/mimer-onecore/issue/UTH-29/stang-listing-vid-tacka-ja-till-erbjudande
=> UTH-29: Close listing when accept offer

package-lock.json, package.json, src/adapters/leasing-adapter/index.ts, src/adapters/tests/leasing-adapter/index.test.ts, src/middlewares/parse-request-body.ts, src/services/lease-service/index.ts, src/services/lease-service/tests/index.test.ts, tsconfig.json
Update application profile
TODO (maybe):
- Parse the response from leasing according to the response schema.
=> UTH-24: update application profile

src/processes/parkingspaces/internal/create-offer.ts
=> UTH-123: only pass first name for create offer email

package-lock.json, package.json, src/processes/parkingspaces/internal/create-offer.ts
* applicationType is now sent to the communication endpoint to send offer emails so that the correct email is sent out
=> Feat:142 Correct Offer Email for Changing Parking Space

src/processes/parkingspaces/internal/create-offer.ts
* The offer email title is now correct
=> Feat:uth-141 Offer Email Title Change

package-lock.json, package.json, src/adapters/tests/leasing-adapter/index.test.ts, src/services/lease-service/index.ts, src/services/lease-service/schemas/client/application-profile/index.ts, src/services/lease-service/tests/index.test.ts, test/factories/application-profile.ts, test/factories/index.ts
Apply changes by https://github.com/Bostads-AB-Mimer/onecore-types/pull/136
=> UTH-164: review status is now an enum

package-lock.json, package.json, src/services/lease-service/schemas/client/application-profile/index.ts
=> fix: supposed to be request params not response params

src/processes/parkingspaces/internal/create-offer.ts
* Any offer created from the Create Offer Process now expires 3 business days later
=> Feat:uth-187 Offer Length Change

src/adapters/leasing-adapter/index.ts, src/processes/parkingspaces/internal/create-note-of-interest.ts
- Allow re-application to change applicationType. Fixes problem where applicant 1 applied with "Hyra en", then withdrew, then re-applied with "Hyra flera" but the type didn't change.
=> UTH-199: Make sure re-application can change the application type

src/services/work-order-service/index.ts, src/services/work-order-service/tests/index.test.ts
=> MIM-383: Send all work orders in one array

src/adapters/leasing-adapter/index.ts, src/services/lease-service/index.ts
=> Feat:UTH-220 Handle Tenants With Leases that is About to End

src/services/work-order-service/schemas.ts
Mer info i https://github.com/Bostads-AB-Mimer/onecore-types/pull/170 och https://github.com/Bostads-AB-Mimer/onecore-work-order/pull/17
=> MIM-492: visa arenden for lagenhet i property tree

src/adapters/property-base-adapter/generated/api-types.ts, src/adapters/property-base-adapter/index.ts, src/services/search-service/index.ts, src/services/search-service/schemas.ts, src/services/search-service/tests/index.test.ts, test/factories/index.ts, test/factories/residence-search-result.ts
Relays residences search result from property base
=> MIM-500: Search residences

src/adapters/property-base-adapter/generated/api-types.ts, src/services/property-base-service/schemas.ts, test/factories/residence-details.ts
https://linear.app/mimer-onecore/issue/MIM-532/grundinformation-hyresobjektstyp
=> MIM-532: add rental information to residence property object

package-lock.json, package.json, src/adapters/leasing-adapter/comments.ts, src/adapters/leasing-adapter/index.ts, src/services/lease-service/comments.ts, src/services/lease-service/index.ts
- Just proxying get/add/remove-requests for comments and comment threads. Happy days!
=> uth-239: Pass along comments ops <---> with a lot of code for nothing

src/adapters/property-base-adapter/generated/api-types.ts, src/adapters/property-base-adapter/index.ts, src/services/property-base-service/index.ts, src/services/property-base-service/schemas.ts
The core part of property-base endpoint to fetch parking space
=> MIM-546: Create endpoint to fetch parking space on rental id - core
